"""add soft delete to cart

Revision ID: 14c72e5e5ca9
Revises: e144066d4b78
Create Date: 2026-09-25 15:40:46.487085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c72e5e5ca9'
down_revision: Union[str, Sequence[str], None] = 'e144066d4b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cart',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'is_deleted')
    # ### end Alembic commands ###