"""add timestamps to cart

Revision ID: 47856d5faaac
Revises: ff1c91933a74
Create Date: 2026-09-25 12:58:30.504446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47856d5faaac'
down_revision: Union[str, Sequence[str], None] = 'ff1c91933a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cart', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'updated_at')
    op.drop_column('cart', 'created_at')
    # ### end Alembic commands ###
