"""add discount percent to products

Revision ID: 67a45cbde9a3
Revises: 8b1c3a497c0f
Create Date: 2026-09-30 12:08:22.347545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a45cbde9a3'
down_revision: Union[str, Sequence[str], None] = '8b1c3a497c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column(
    'discount_percent',
    sa.Float(),
    server_default='0',
    nullable=False
)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percent')
    # ### end Alembic commands ###