"""add soft delete to cart items

Revision ID: 7a92755cbfc7
Revises: 14c72e5e5ca9
Create Date: 2026-09-25 15:46:42.031895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a92755cbfc7'
down_revision: Union[str, Sequence[str], None] = '14c72e5e5ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cart_items',
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('cart', sa.Column('is_deleted', sa.BOOLEAN(), nullable=False, server_default=sa.text('false')))