"""add soft delete to categories

Revision ID: a05406e5210c
Revises: ed50cf44fb18
Create Date: 2026-09-25 15:28:33.633134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05406e5210c'
down_revision: Union[str, Sequence[str], None] = 'ed50cf44fb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'categories',
    sa.Column(
        'is_deleted',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
