"""add soft delete to users

Revision ID: e144066d4b78
Revises: a05406e5210c
Create Date: 2026-09-25 15:36:20.462968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e144066d4b78'
down_revision: Union[str, Sequence[str], None] = 'a05406e5210c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'is_deleted',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
